name: Build and deploy ASP.Net Core app to Azure Web App - webapp-dev-ukw-001

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Publish .NET app
        run: dotnet publish ./DotNetCoreSqlDb.csproj -c Release -o ./publish

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9964DDA4CA5840ADB5E50E6842777356 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1C0CE0A86263400283D4BFB9BFC6D36B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_48C88CBC351F4339B5A25E98ECEBECFF }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'webapp-dev-ukw-001'
          slot-name: 'Production'
          package: .
